services:
    nginx : 
        container_name  : nginx
        image   : nginx:1337
        build   : requirements/nginx
        volumes :
            - WordPress:/var/www/html
        ports:
            - 443:443
        depends_on :
            wordpress :
                condition : service_healthy
            adminer :
                condition : service_healthy
        restart: always

    mariadb :
        container_name  : mariadb
        image   : mariadb:1337
        build   : requirements/mariadb
        environment :
            DB_PORT : ${DB_PORT}
            DB_NAME : ${DB_NAME}
            DB_USER : ${DB_USER}
            DB_ROOT_PWD : ${DB_ROOT_PWD}
            DB_USER_PWD : ${DB_USER_PWD}
        volumes :
            - DataBase:/var/lib/mysql
        restart: always
    
    wordpress :
        container_name  : wordpress
        image   : wordpress:1337
        build   : requirements/wordpress
        environment :
          DB_NAME   : ${DB_NAME}
          DB_HOST   : ${DB_HOST}
          DB_PORT   : ${DB_PORT}
          DB_USER   : ${DB_USER}
          DB_USER_PWD   : ${DB_USER_PWD}
          WP_URL    : ${WP_URL}
          WP_TITLE  : ${WP_TITLE}
          WP_ADMIN  : ${WP_ADMIN}
          WP_ADMIN_PWD  : ${WP_ADMIN_PWD}
          WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
          WP_USER   :  ${WP_USER}
          WP_USER_PWD  :  ${WP_USER_PWD}
          WP_USER_EMAIL:  ${WP_USER_EMAIL}
          WP_USER_ROLE:  ${WP_USER_ROLE}
        volumes :
          - WordPress:/var/www/html
        depends_on :
            redis :
                condition : service_healthy
            mariadb :
                condition : service_healthy
        restart: always

    adminer :
        container_name  : adminer
        image   : adminer:1337
        build   : requirements/bonus/adminer
        volumes :
          - WordPress:/var/www/html
        depends_on :
            mariadb :
                condition : service_healthy
        restart: always
    
    redis :
        container_name  : redis
        image   : redis:1337
        build   : requirements/bonus/redis
        restart: always

    ftp:
        container_name: ftp
        image: ftp:1337
        build:
            args:
                - FTP_USR=${FTP_USR}
                - FTP_PWD=${FTP_PWD}
            context: requirements/bonus/ftp-server
        volumes :
            - WordPress:/var/www/html
        ports:
            - "21:21"
            - "21100-21110:21100-21110"
        depends_on :
            wordpress :
                condition : service_healthy
        restart: always
        network_mode: bridge 

    cadvisor :
        container_name  : cadvisor
        image   : cadvisor:1337
        build   : requirements/bonus/cadvisor
        ports :
            - 8080:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro 
            - /sys:/sys:ro 
            - /var/lib/docker/:/var/lib/docker:ro
        restart: always

    calculator:
        container_name  : calculator
        image:  calculator:1337 
        build:  requirements/bonus/calculator
        ports :
            - 8081:8081
        restart: always

networks:
    default :
        name    : inception
        driver  : bridge

volumes:
    DataBase :
        name    : DataBase
        driver  : local
        driver_opts :
            type : none
            o : bind
            device: /home/hael-mou/data/DataBase

    WordPress :
        name    : WordPress
        driver  : local
        driver_opts:
            type : none
            o : bind
            device: /home/hael-mou/data/WordPress