
version: '3'

services:
    nginx:
        container_name: nginx
        image:  nginx:1337
        build:  requirements/nginx
        volumes:
          - wordpress:/var/www/wordpress
        networks:
          - inception
        ports:
          - 443:443

    mariadb:
        container_name: mariadb
        image:  mariadb:1337
        build:  requirements/mariadb
        env_file: .env
        environment:
          - DATABASE_NAME=${DATABASE_NAME}
          - MARIADB_USER=${MARIADB_USER}
          - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
          - MARIADB_USER_PASSWORD=${MARIADB_USER_PASSWORD}
        volumes:
          - DB:/var/lib/mysql
        networks:
          - inception
        ports:
          - 3306:3306

networks:
    inception:
        driver: bridge

volumes:
    DB:
    wordpress: